// Adapted for this local experiment from FlapCred_Worker_Demo.zip (SHA256
// 34bf9e7dc6392f0576863a7a2f26ff24b42c61a4332d5925d27566eaad670b58).
// Redistribution/license review is required before a public release.
// ARCAT miner core: keccak256 over the exact bytes the contract hashes, with a precomputed midstate.
//
// digest = keccak256(abi.encode(DOMAIN, chainId, contract, anchorHash, miner, nonce))  -> 192 bytes.
// keccak256 absorbs 136-byte blocks, so block 1 (bytes 0..135) never changes while mining a given
// anchor: we permute it once, keep that "midstate", and every attempt only runs the second permutation.
//
// Lanes are 64-bit, emulated with pairs of 32-bit ints: s[2*i] = low half, s[2*i+1] = high half.

const RC = [
  0x00000001, 0x00000000, 0x00008082, 0x00000000, 0x0000808a, 0x80000000,
  0x80008000, 0x80000000, 0x0000808b, 0x00000000, 0x80000001, 0x00000000,
  0x80008081, 0x80000000, 0x00008009, 0x80000000, 0x0000008a, 0x00000000,
  0x00000088, 0x00000000, 0x80008009, 0x00000000, 0x8000000a, 0x00000000,
  0x8000808b, 0x00000000, 0x0000008b, 0x80000000, 0x00008089, 0x80000000,
  0x00008003, 0x80000000, 0x00008002, 0x80000000, 0x00000080, 0x80000000,
  0x0000800a, 0x00000000, 0x8000000a, 0x80000000, 0x80008081, 0x80000000,
  0x00008080, 0x80000000, 0x80000001, 0x00000000, 0x80008008, 0x80000000,
];
// rho rotation for lane index x + 5y, and pi destination
const ROT = [
  0, 1, 62, 28, 27, 36, 44, 6, 55, 20, 3, 10, 43, 25, 39, 41, 45, 15, 21, 8, 18,
  2, 61, 56, 14,
];
const PI = new Array(25);
for (let x = 0; x < 5; x++)
  for (let y = 0; y < 5; y++) PI[x + 5 * y] = y + 5 * ((2 * x + 3 * y) % 5);

const B = new Int32Array(50);
const C = new Int32Array(10);

/** keccak-f[1600] in place on a 50-int state. */
export function keccakF(s) {
  for (let round = 0; round < 24; round++) {
    // theta
    for (let x = 0; x < 5; x++) {
      C[2 * x] =
        s[2 * x] ^
        s[2 * x + 10] ^
        s[2 * x + 20] ^
        s[2 * x + 30] ^
        s[2 * x + 40];
      C[2 * x + 1] =
        s[2 * x + 1] ^
        s[2 * x + 11] ^
        s[2 * x + 21] ^
        s[2 * x + 31] ^
        s[2 * x + 41];
    }
    for (let x = 0; x < 5; x++) {
      const x1 = (x + 1) % 5,
        x4 = (x + 4) % 5;
      const lo = C[2 * x1],
        hi = C[2 * x1 + 1];
      const dlo = C[2 * x4] ^ ((lo << 1) | (hi >>> 31));
      const dhi = C[2 * x4 + 1] ^ ((hi << 1) | (lo >>> 31));
      for (let y = 0; y < 25; y += 5) {
        s[2 * (x + y)] ^= dlo;
        s[2 * (x + y) + 1] ^= dhi;
      }
    }
    // rho + pi
    for (let i = 0; i < 25; i++) {
      const lo = s[2 * i],
        hi = s[2 * i + 1],
        r = ROT[i],
        j = PI[i];
      if (r === 0) {
        B[2 * j] = lo;
        B[2 * j + 1] = hi;
      } else if (r < 32) {
        B[2 * j] = (lo << r) | (hi >>> (32 - r));
        B[2 * j + 1] = (hi << r) | (lo >>> (32 - r));
      } else if (r === 32) {
        B[2 * j] = hi;
        B[2 * j + 1] = lo;
      } else {
        const q = r - 32;
        B[2 * j] = (hi << q) | (lo >>> (32 - q));
        B[2 * j + 1] = (lo << q) | (hi >>> (32 - q));
      }
    }
    // chi
    for (let y = 0; y < 25; y += 5) {
      for (let x = 0; x < 5; x++) {
        const a = 2 * (x + y),
          b = 2 * (((x + 1) % 5) + y),
          c = 2 * (((x + 2) % 5) + y);
        s[a] = B[a] ^ (~B[b] & B[c]);
        s[a + 1] = B[a + 1] ^ (~B[b + 1] & B[c + 1]);
      }
    }
    // iota
    s[0] ^= RC[2 * round];
    s[1] ^= RC[2 * round + 1];
  }
}

// GENERATED by gen_unrolled.py logic (kept inline in keccak_fast.js): keccak-f[1600], fully unrolled per round.
export function keccakFast(s) {
  let a0 = s[0],
    a1 = s[1],
    a2 = s[2],
    a3 = s[3],
    a4 = s[4],
    a5 = s[5],
    a6 = s[6],
    a7 = s[7],
    a8 = s[8],
    a9 = s[9],
    a10 = s[10],
    a11 = s[11],
    a12 = s[12],
    a13 = s[13],
    a14 = s[14],
    a15 = s[15],
    a16 = s[16],
    a17 = s[17],
    a18 = s[18],
    a19 = s[19],
    a20 = s[20],
    a21 = s[21],
    a22 = s[22],
    a23 = s[23],
    a24 = s[24],
    a25 = s[25],
    a26 = s[26],
    a27 = s[27],
    a28 = s[28],
    a29 = s[29],
    a30 = s[30],
    a31 = s[31],
    a32 = s[32],
    a33 = s[33],
    a34 = s[34],
    a35 = s[35],
    a36 = s[36],
    a37 = s[37],
    a38 = s[38],
    a39 = s[39],
    a40 = s[40],
    a41 = s[41],
    a42 = s[42],
    a43 = s[43],
    a44 = s[44],
    a45 = s[45],
    a46 = s[46],
    a47 = s[47],
    a48 = s[48],
    a49 = s[49];
  let b0,
    b1,
    b2,
    b3,
    b4,
    b5,
    b6,
    b7,
    b8,
    b9,
    b10,
    b11,
    b12,
    b13,
    b14,
    b15,
    b16,
    b17,
    b18,
    b19,
    b20,
    b21,
    b22,
    b23,
    b24,
    b25,
    b26,
    b27,
    b28,
    b29,
    b30,
    b31,
    b32,
    b33,
    b34,
    b35,
    b36,
    b37,
    b38,
    b39,
    b40,
    b41,
    b42,
    b43,
    b44,
    b45,
    b46,
    b47,
    b48,
    b49;
  let c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, dl, dh;
  for (let r = 0; r < 48; r += 2) {
    c0 = a0 ^ a10 ^ a20 ^ a30 ^ a40;
    c1 = a1 ^ a11 ^ a21 ^ a31 ^ a41;
    c2 = a2 ^ a12 ^ a22 ^ a32 ^ a42;
    c3 = a3 ^ a13 ^ a23 ^ a33 ^ a43;
    c4 = a4 ^ a14 ^ a24 ^ a34 ^ a44;
    c5 = a5 ^ a15 ^ a25 ^ a35 ^ a45;
    c6 = a6 ^ a16 ^ a26 ^ a36 ^ a46;
    c7 = a7 ^ a17 ^ a27 ^ a37 ^ a47;
    c8 = a8 ^ a18 ^ a28 ^ a38 ^ a48;
    c9 = a9 ^ a19 ^ a29 ^ a39 ^ a49;
    dl = c8 ^ ((c2 << 1) | (c3 >>> 31));
    dh = c9 ^ ((c3 << 1) | (c2 >>> 31));
    a0 ^= dl;
    a1 ^= dh;
    a10 ^= dl;
    a11 ^= dh;
    a20 ^= dl;
    a21 ^= dh;
    a30 ^= dl;
    a31 ^= dh;
    a40 ^= dl;
    a41 ^= dh;
    dl = c0 ^ ((c4 << 1) | (c5 >>> 31));
    dh = c1 ^ ((c5 << 1) | (c4 >>> 31));
    a2 ^= dl;
    a3 ^= dh;
    a12 ^= dl;
    a13 ^= dh;
    a22 ^= dl;
    a23 ^= dh;
    a32 ^= dl;
    a33 ^= dh;
    a42 ^= dl;
    a43 ^= dh;
    dl = c2 ^ ((c6 << 1) | (c7 >>> 31));
    dh = c3 ^ ((c7 << 1) | (c6 >>> 31));
    a4 ^= dl;
    a5 ^= dh;
    a14 ^= dl;
    a15 ^= dh;
    a24 ^= dl;
    a25 ^= dh;
    a34 ^= dl;
    a35 ^= dh;
    a44 ^= dl;
    a45 ^= dh;
    dl = c4 ^ ((c8 << 1) | (c9 >>> 31));
    dh = c5 ^ ((c9 << 1) | (c8 >>> 31));
    a6 ^= dl;
    a7 ^= dh;
    a16 ^= dl;
    a17 ^= dh;
    a26 ^= dl;
    a27 ^= dh;
    a36 ^= dl;
    a37 ^= dh;
    a46 ^= dl;
    a47 ^= dh;
    dl = c6 ^ ((c0 << 1) | (c1 >>> 31));
    dh = c7 ^ ((c1 << 1) | (c0 >>> 31));
    a8 ^= dl;
    a9 ^= dh;
    a18 ^= dl;
    a19 ^= dh;
    a28 ^= dl;
    a29 ^= dh;
    a38 ^= dl;
    a39 ^= dh;
    a48 ^= dl;
    a49 ^= dh;
    b0 = a0;
    b1 = a1;
    b20 = (a2 << 1) | (a3 >>> 31);
    b21 = (a3 << 1) | (a2 >>> 31);
    b40 = (a5 << 30) | (a4 >>> 2);
    b41 = (a4 << 30) | (a5 >>> 2);
    b10 = (a6 << 28) | (a7 >>> 4);
    b11 = (a7 << 28) | (a6 >>> 4);
    b30 = (a8 << 27) | (a9 >>> 5);
    b31 = (a9 << 27) | (a8 >>> 5);
    b32 = (a11 << 4) | (a10 >>> 28);
    b33 = (a10 << 4) | (a11 >>> 28);
    b2 = (a13 << 12) | (a12 >>> 20);
    b3 = (a12 << 12) | (a13 >>> 20);
    b22 = (a14 << 6) | (a15 >>> 26);
    b23 = (a15 << 6) | (a14 >>> 26);
    b42 = (a17 << 23) | (a16 >>> 9);
    b43 = (a16 << 23) | (a17 >>> 9);
    b12 = (a18 << 20) | (a19 >>> 12);
    b13 = (a19 << 20) | (a18 >>> 12);
    b14 = (a20 << 3) | (a21 >>> 29);
    b15 = (a21 << 3) | (a20 >>> 29);
    b34 = (a22 << 10) | (a23 >>> 22);
    b35 = (a23 << 10) | (a22 >>> 22);
    b4 = (a25 << 11) | (a24 >>> 21);
    b5 = (a24 << 11) | (a25 >>> 21);
    b24 = (a26 << 25) | (a27 >>> 7);
    b25 = (a27 << 25) | (a26 >>> 7);
    b44 = (a29 << 7) | (a28 >>> 25);
    b45 = (a28 << 7) | (a29 >>> 25);
    b46 = (a31 << 9) | (a30 >>> 23);
    b47 = (a30 << 9) | (a31 >>> 23);
    b16 = (a33 << 13) | (a32 >>> 19);
    b17 = (a32 << 13) | (a33 >>> 19);
    b36 = (a34 << 15) | (a35 >>> 17);
    b37 = (a35 << 15) | (a34 >>> 17);
    b6 = (a36 << 21) | (a37 >>> 11);
    b7 = (a37 << 21) | (a36 >>> 11);
    b26 = (a38 << 8) | (a39 >>> 24);
    b27 = (a39 << 8) | (a38 >>> 24);
    b28 = (a40 << 18) | (a41 >>> 14);
    b29 = (a41 << 18) | (a40 >>> 14);
    b48 = (a42 << 2) | (a43 >>> 30);
    b49 = (a43 << 2) | (a42 >>> 30);
    b18 = (a45 << 29) | (a44 >>> 3);
    b19 = (a44 << 29) | (a45 >>> 3);
    b38 = (a47 << 24) | (a46 >>> 8);
    b39 = (a46 << 24) | (a47 >>> 8);
    b8 = (a48 << 14) | (a49 >>> 18);
    b9 = (a49 << 14) | (a48 >>> 18);
    a0 = b0 ^ (~b2 & b4);
    a1 = b1 ^ (~b3 & b5);
    a2 = b2 ^ (~b4 & b6);
    a3 = b3 ^ (~b5 & b7);
    a4 = b4 ^ (~b6 & b8);
    a5 = b5 ^ (~b7 & b9);
    a6 = b6 ^ (~b8 & b0);
    a7 = b7 ^ (~b9 & b1);
    a8 = b8 ^ (~b0 & b2);
    a9 = b9 ^ (~b1 & b3);
    a10 = b10 ^ (~b12 & b14);
    a11 = b11 ^ (~b13 & b15);
    a12 = b12 ^ (~b14 & b16);
    a13 = b13 ^ (~b15 & b17);
    a14 = b14 ^ (~b16 & b18);
    a15 = b15 ^ (~b17 & b19);
    a16 = b16 ^ (~b18 & b10);
    a17 = b17 ^ (~b19 & b11);
    a18 = b18 ^ (~b10 & b12);
    a19 = b19 ^ (~b11 & b13);
    a20 = b20 ^ (~b22 & b24);
    a21 = b21 ^ (~b23 & b25);
    a22 = b22 ^ (~b24 & b26);
    a23 = b23 ^ (~b25 & b27);
    a24 = b24 ^ (~b26 & b28);
    a25 = b25 ^ (~b27 & b29);
    a26 = b26 ^ (~b28 & b20);
    a27 = b27 ^ (~b29 & b21);
    a28 = b28 ^ (~b20 & b22);
    a29 = b29 ^ (~b21 & b23);
    a30 = b30 ^ (~b32 & b34);
    a31 = b31 ^ (~b33 & b35);
    a32 = b32 ^ (~b34 & b36);
    a33 = b33 ^ (~b35 & b37);
    a34 = b34 ^ (~b36 & b38);
    a35 = b35 ^ (~b37 & b39);
    a36 = b36 ^ (~b38 & b30);
    a37 = b37 ^ (~b39 & b31);
    a38 = b38 ^ (~b30 & b32);
    a39 = b39 ^ (~b31 & b33);
    a40 = b40 ^ (~b42 & b44);
    a41 = b41 ^ (~b43 & b45);
    a42 = b42 ^ (~b44 & b46);
    a43 = b43 ^ (~b45 & b47);
    a44 = b44 ^ (~b46 & b48);
    a45 = b45 ^ (~b47 & b49);
    a46 = b46 ^ (~b48 & b40);
    a47 = b47 ^ (~b49 & b41);
    a48 = b48 ^ (~b40 & b42);
    a49 = b49 ^ (~b41 & b43);
    a0 ^= RC[r];
    a1 ^= RC[r + 1];
  }
  s[0] = a0;
  s[1] = a1;
  s[2] = a2;
  s[3] = a3;
  s[4] = a4;
  s[5] = a5;
  s[6] = a6;
  s[7] = a7;
  s[8] = a8;
  s[9] = a9;
  s[10] = a10;
  s[11] = a11;
  s[12] = a12;
  s[13] = a13;
  s[14] = a14;
  s[15] = a15;
  s[16] = a16;
  s[17] = a17;
  s[18] = a18;
  s[19] = a19;
  s[20] = a20;
  s[21] = a21;
  s[22] = a22;
  s[23] = a23;
  s[24] = a24;
  s[25] = a25;
  s[26] = a26;
  s[27] = a27;
  s[28] = a28;
  s[29] = a29;
  s[30] = a30;
  s[31] = a31;
  s[32] = a32;
  s[33] = a33;
  s[34] = a34;
  s[35] = a35;
  s[36] = a36;
  s[37] = a37;
  s[38] = a38;
  s[39] = a39;
  s[40] = a40;
  s[41] = a41;
  s[42] = a42;
  s[43] = a43;
  s[44] = a44;
  s[45] = a45;
  s[46] = a46;
  s[47] = a47;
  s[48] = a48;
  s[49] = a49;
}

function xorBytesIntoState(s, bytes, laneCount) {
  for (let i = 0; i < laneCount; i++) {
    const o = i * 8;
    s[2 * i] ^=
      bytes[o] |
      (bytes[o + 1] << 8) |
      (bytes[o + 2] << 16) |
      (bytes[o + 3] << 24);
    s[2 * i + 1] ^=
      bytes[o + 4] |
      (bytes[o + 5] << 8) |
      (bytes[o + 6] << 16) |
      (bytes[o + 7] << 24);
  }
}

const hexToBytes = (h) => {
  h = h.replace(/^0x/, "");
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++)
    out[i] = parseInt(h.substr(2 * i, 2), 16);
  return out;
};
const word = (hex) => {
  const b = hexToBytes(hex.replace(/^0x/, "").padStart(64, "0"));
  return b;
};

/**
 * Prepare a mining job. All inputs are 0x-hex strings (chainId may be a number).
 * Returns { mid, tail } where mid is the state after block 1 and tail is block 2's constant bytes.
 */
export function prepare({
  domain,
  chainId,
  contract,
  anchorHash,
  miner,
  nonceHigh,
}) {
  const msg = new Uint8Array(192);
  msg.set(word(domain), 0);
  msg.set(word(BigInt(chainId).toString(16)), 32);
  msg.set(word(contract), 64);
  msg.set(word(anchorHash), 96);
  msg.set(word(miner), 128);
  msg.set(word(nonceHigh || "0"), 160);
  msg.fill(0, 184, 192); // the low 8 bytes of the nonce are written per attempt

  const mid = new Int32Array(50);
  xorBytesIntoState(mid, msg.subarray(0, 136), 17);
  keccakF(mid);

  const tail = new Uint8Array(136); // block 2: bytes 136..191, then keccak padding
  tail.set(msg.subarray(136, 192), 0);
  tail[56] ^= 0x01;
  tail[135] ^= 0x80;
  const tailLanes = new Int32Array(34);
  xorBytesIntoState(tailLanes, tail, 17);
  return { mid, tailLanes, msg };
}

const bswap = (v) =>
  ((v & 0xff) << 24) | ((v & 0xff00) << 8) | ((v >>> 8) & 0xff00) | (v >>> 24);

/**
 * Try `count` nonces starting at `start` (the low 64 bits of the nonce: hiWord:loWord).
 * Returns the first counter whose digest's top 64 bits are below targetTop (as [hi32, lo32] unsigned),
 * or -1. The caller verifies the full 256-bit comparison.
 */
export function search(job, hiWord, start, count, targetHi, targetLo) {
  const s = new Int32Array(50);
  const { mid, tailLanes } = job;
  // nonce low 8 bytes live in block-2 lane 6 (bytes 48..55), big-endian
  const laneLoFixed = bswap(hiWord);
  for (let n = 0; n < count; n++) {
    const ctr = (start + n) >>> 0;
    for (let i = 0; i < 34; i++) s[i] = mid[i] ^ tailLanes[i];
    for (let i = 34; i < 50; i++) s[i] = mid[i];
    s[12] ^= laneLoFixed;
    s[13] ^= bswap(ctr);
    keccakFast(s);
    // digest bytes 0..3 = low half of lane 0 (little-endian) -> top 32 bits of the uint256
    const top = bswap(s[0]) >>> 0;
    if (top < targetHi || (top === targetHi && (bswap(s[1]) >>> 0) <= targetLo))
      return ctr;
  }
  return -1;
}

/** Full digest for one nonce (hex), used to double-check a candidate before sending it. */
export function digestHex(job, hiWord, ctr) {
  const s = new Int32Array(50);
  for (let i = 0; i < 50; i++)
    s[i] = job.mid[i] ^ (i < 34 ? job.tailLanes[i] : 0);
  s[12] ^= bswap(hiWord);
  s[13] ^= bswap(ctr >>> 0);
  keccakF(s);
  let hex = "";
  for (let i = 0; i < 4; i++) {
    const lo = s[2 * i],
      hi = s[2 * i + 1];
    for (const v of [lo, hi])
      for (let k = 0; k < 4; k++)
        hex += ((v >>> (8 * k)) & 0xff).toString(16).padStart(2, "0");
  }
  return "0x" + hex;
}

/** The uint256 nonce the contract will receive: nonceHigh's top 24 bytes, then hiWord, then ctr. */
export function nonceHex(nonceHigh, hiWord, ctr) {
  const top = (nonceHigh || "0")
    .replace(/^0x/, "")
    .padStart(64, "0")
    .slice(0, 48);
  return (
    "0x" +
    top +
    (hiWord >>> 0).toString(16).padStart(8, "0") +
    (ctr >>> 0).toString(16).padStart(8, "0")
  );
}
